[package]
name = "ch01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.5", features = ["derive"] }
rand = "0.8"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
